- name: Скачивание новой версии 1С с FTP
  get_url:
    url: "ftp://{{ ftp_user }}:{{ ftp_password }}@mail.nevis.spb.ru/1s_run/1C_Enterprise_{{ 1s_version }}.run"
    dest: "/tmp/1C_Enterprise_{{ 1s_version }}.run"
    mode: '0755'
