- name: Определение имени файла из полного пути
  set_fact:
    ftp_file: "{{ ftp_full_path | basename }}"

- name: Скачивание новой версии 1С с FTP
  get_url:
    url: "ftp://{{ ftp_user }}:{{ ftp_password }}@{{ ftp_full_path | regex_replace('ftp://[^/]+', '') }}"
    dest: "/tmp/{{ ftp_file }}"
    mode: '0755'   
