---
- name: Поиск установленной версии 1С
  include_tasks: find_installed.yml

- name: Версия 1с
  debug:
    var: current_version  

- name: Остановка служб 1С перед удалением
  include_tasks: stop_services.yml
  when: current_version != "" and current_version != _1s_version

- name: Удаление старой версии 1С
  include_tasks: remove_old.yml
  when: current_version != "" and current_version != _1s_version

- name: Скачивание новой версии 1С
  include_tasks: download.yml
  when: current_version != "" and current_version != _1s_version

- name: Установка новой версии 1С
  include_tasks: install.yml
  when: current_version != "" and current_version != _1s_version

