- name: Остановка службы 1С
  systemd:
    name: "{{ current_version_service }}"
    state: stopped
  when: current_version_service is defined
  register: stop_service
  changed_when: stop_service.changed